/**
 * @author Isak Aasemoen Aardal
 */

// import Dice from "./Dice.js"

// export default class{

//     _root = "root";
//     _inputElement = document.getElementById(_root).querySelector("data-dicebutton");
//     _outputElement;

//     constructor(root) {
//         this._root = root
//         this.run = this.run.bind(this);
//         this.rollDice = this.rollDice.bind(this);
//     }

//     run() {
//         alert("lmao");
//         btRef = document.getElementById(this._root).querySelector("data-dicebutton");
//         btRef.addEventListener("click", this.rollDice);
//         this.rollDice = this.rollDice.bind(this);
//         diceoutput = document.getElementById(this._root).querySelector("data-diceoutput");
//         this.diceoutput.innerHtml = _outputElement;
//     }

//     rollDice() {
//         Dice.roll();
//         this._outputElement = Dice.getValue();
//     }
// }

// Generated by CoffeeScript 2.4.1
(function() {
    var DiceController;
  
    DiceController = (function() {
      class DiceController {
        constructor(root = "root") {
          this._root = root;
          this.run = this.run.bind(this);
          this.rollDice = this.rollDice.bind(this);
        }
  
        run() {
          var btRef, diceOutput;
          alert('Running');
          btRef = document.getElementById(this._root).querySelector("data-dicebutton");
          btRef.addEventListener("click", this.rollDice);
          diceOutput = document.getElementById(this._root).querySelector("data-dicebutton");
          return this.diceOutput.innerHtml = this._outputElement;
        }
  
        rollDice() {
          alert('Rolling Dice');
          Dice.roll;
          return this._outputElement = Dice.getValue();
        }
  
      };
  
      DiceController.prototype._root = "root";
  
      DiceController.prototype._inputElement = document.getElementById(_root).querySelector("data-dicebutton");
  
      DiceController.prototype._outputElement = "no value";
  
      return DiceController;
  
    }).call(this);
  
  }).call(this);